server:
  #port: 8080
  http2:
    enabled: true
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.jks
    key-store-password: changeit
    trust-store-password: changeit
    trust-store: classpath:cacerts.jks

spring:
  application:
    name: transaction-bff
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client_id: ${spring.application.name}
      transaction-id-prefix: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    port: 6379
    host: localhost
    timeout: 5000

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://localhost:4317

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.coffeeandit.com.br/auth/realms/master

springdoc:
  swagger-ui:
    path: /swagger-ui.html

limites:
  url: http://localhost:8081
transaction:
  url: http://localhost:8082

app:
  topic: transaction

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true