spring:
  application:
    name: transaction-bff
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client_id: ${spring.application.name}
      transaction-id-prefix: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    port: 6379
    host: localhost
    timeout: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html

limites:
  url: http://localhost:8081

app:
  topic: transaction